# Generated by Django 5.0.4 on 2024-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Presentacion', models.CharField(max_length=30)),
                ('Fecha', models.DateField()),
                ('Cantidad', models.PositiveBigIntegerField()),
            ],
        ),
    ]
