# Generated by Django 5.0.4 on 2024-05-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CambioStock',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveBigIntegerField()),
                ('tipo_cambio', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=100)),
                ('fecha_c', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productos')),
            ],
        ),
    ]
